package ru.test.logic.AuthGame.Exceptions;

//Игрок, который пытается выполнить действие, уже проиграл
public class PlayerHasLostException extends GameException {
}
